### ISSUE TITLE
无法指定(x,y)坐标到较大的位置

### ISSUE THREAD

**Issue by CornWorld** [Duanyll/LuoguPaintboardPro#4]
当左上坐标为(x=0,y=0)时可以正常绘制,但是超过一定值就不能绘制了

![image](https://user-images.githubusercontent.com/43746030/103434439-4556d780-4c3c-11eb-8852-d504db5f83c9.png)

**Comment by Duanyll** [comment]
你这应该确实超出范围了
画板本身只有1000x600
